services:
  libuv-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: libuv-dev
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: tail -f /dev/null


